# Generated by Django 4.2.10 on 2025-01-27 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 1, 27, 13, 5, 36, 600973))),
            ],
            options={
                'db_table': 'Buy rates',
            },
        ),
        migrations.CreateModel(
            name='Sell_rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 1, 27, 13, 5, 36, 601100))),
            ],
            options={
                'db_table': 'Sell rates',
            },
        ),
    ]
