# Generated by Django 4.2.10 on 2025-01-27 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_rates',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 13, 5, 53, 285248)),
        ),
        migrations.AlterField(
            model_name='sell_rates',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 13, 5, 53, 285362)),
        ),
    ]
