# Generated by Django 4.2.10 on 2025-01-27 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_buy_rates_code_alter_buy_rates_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_rates',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 13, 11, 10, 268655)),
        ),
        migrations.AlterField(
            model_name='sell_rates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
