# Generated by Django 4.2.10 on 2025-01-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_currency_delete_buy_rates_delete_sell_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
