# Generated by Django 4.2.10 on 2025-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_currency_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='order',
            field=models.PositiveIntegerField(default=0, max_length=20),
        ),
    ]
