# Generated by Django 4.2.10 on 2025-01-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_alter_currency_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
