# Generated by Django 4.2.10 on 2025-01-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_alter_currency_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices_fee', models.FloatField(default=0.2, help_text='Prices fee percentage (e.g., 0.2 for 0.2%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
