# Generated by Django 4.2.10 on 2025-01-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='show_prices_fee',
            field=models.BooleanField(default=True, help_text='Show or hide prices fee on the homepage'),
        ),
    ]
