# Generated by Django 4.2.10 on 2025-01-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_configuration_show_prices_fee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuration',
            table='configuration',
        ),
        migrations.AlterModelTable(
            name='currency',
            table='currency',
        ),
    ]
